# Generated by Django 2.2.10 on 2020-04-19 17:50

import json
from django.db import migrations
from django.conf import settings


def create_states(apps, schema_editor):

    State = apps.get_model('core', 'State')

    json_file = json.loads(open('%s/backup/states.json' % settings.BASE_DIR, 'r').read())
        
    for state in json_file:
        State.objects.get_or_create(**state)


def create_cities(apps, schema_editor):

    State = apps.get_model('core', 'State')
    City = apps.get_model('core', 'City')

    json_file = json.loads(open('%s/backup/cities.json' % settings.BASE_DIR, 'r').read())
        
    for city in json_file:
        state = State.objects.get(uf=city.get('state'))
        City.objects.get_or_create(name=city.get('name'), state=state)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_states),
        migrations.RunPython(create_cities)
    ]
