# Generated by Django 2.2.10 on 2020-04-20 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200419_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['created_at'], 'verbose_name': 'Dia da Semana', 'verbose_name_plural': 'Dias da Semana'},
        ),
    ]
