# Generated by Django 2.2.10 on 2020-05-04 19:24

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200419_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('avaliation_days', models.PositiveSmallIntegerField(verbose_name='Dias de avaliação')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor mensal')),
                ('no_interest_installment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Número de Parcelas sem júros')),
            ],
            options={
                'verbose_name': 'Geral',
            },
        ),
    ]
