# Generated by Django 2.2.10 on 2020-06-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200531_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hashtags',
            field=models.TextField(blank=True, null=True, verbose_name='Hashtags'),
        ),
    ]
