# Generated by Django 2.2.10 on 2020-05-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Geral', 'verbose_name_plural': 'Geral'},
        ),
    ]
