# Generated by Django 2.2.10 on 2020-04-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200420_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typepay',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de pagamento', 'verbose_name_plural': 'Tipos de pagamento'},
        ),
    ]
