# Generated by Django 2.2.10 on 2020-05-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200504_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='avaliation_days',
            new_name='trial_period',
        ),
        migrations.RemoveField(
            model_name='config',
            name='no_interest_installment',
        ),
        migrations.AddField(
            model_name='config',
            name='plan_code',
            field=models.CharField(default='', max_length=255, verbose_name='Código do plano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='plan_description',
            field=models.TextField(default='', verbose_name='Descrição do plano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='plan_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do plano'),
            preserve_default=False,
        ),
    ]
