# Generated by Django 2.2.10 on 2020-04-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdone',
            options={'ordering': ['service', '-created_at'], 'verbose_name': 'Trabalho realizado', 'verbose_name_plural': 'Trabalhos realizados'},
        ),
    ]
