# Generated by Django 2.2.10 on 2020-05-03 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200502_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='profile',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiration',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 1), null=True, verbose_name='Expiração'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=255, verbose_name='Número')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='customer.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['-created_at'],
            },
        ),
    ]
