# Generated by Django 2.2.10 on 2020-04-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200419_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomousservice',
            name='type_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomous_services', to='core.TypePay', verbose_name='Tipo de Pagamento'),
        ),
    ]
