# Generated by Django 2.2.10 on 2020-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200503_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
