# Generated by Django 2.2.10 on 2020-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='text_cancel',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo Cancelamento'),
        ),
    ]
