# Generated by Django 2.2.10 on 2020-05-04 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 2), null=True, verbose_name='Expiração'),
        ),
    ]
