# Generated by Django 2.2.10 on 2020-05-04 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200504_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Expiração'),
        ),
        migrations.CreateModel(
            name='PayRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('paymentLink', models.URLField(verbose_name='Link Pagamento')),
                ('payment_type', models.CharField(choices=[('ticket', 'Boleto'), ('credit_card', 'Cartão de Crédito')], max_length=255, verbose_name='Tipo de Pagamento')),
                ('status', models.CharField(choices=[('1', 'Aguardando pagamento'), ('2', 'Em análise'), ('3', 'Pago'), ('4', 'Disponível'), ('5', 'Em disputa'), ('6', 'Devolvido'), ('7', 'Cancelado'), ('8', 'Debitado'), ('9', 'Retenção temporária')], default='1', max_length=1, verbose_name='Status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_requests', to='customer.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-created_at'],
            },
        ),
    ]
