# Generated by Django 2.2.10 on 2020-05-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200504_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrequest',
            old_name='paymentLink',
            new_name='payment_link',
        ),
    ]
