# Generated by Django 2.2.10 on 2020-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_profile_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrequest',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Pagamento'),
        ),
    ]
