# Generated by Django 2.2.10 on 2020-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200603_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lng',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
    ]
