# Generated by Django 2.2.10 on 2020-06-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200604_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onesignal',
            field=models.CharField(default='', max_length=255, verbose_name='Onesignal'),
            preserve_default=False,
        ),
    ]
