# Generated by Django 2.2.10 on 2020-06-05 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200605_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='customer.Profile', verbose_name='Profissional'),
        ),
        migrations.CreateModel(
            name='ServiceProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('recused', 'Recusado'), ('approved', 'Aprovado'), ('requested', 'Aguardando aprovação')], max_length=255, verbose_name='Status')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='customer.Profile', verbose_name='Profissional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='customer.Service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
