# Generated by Django 2.2.10 on 2020-06-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200603_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lat',
            field=models.FloatField(max_length=255, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lng',
            field=models.FloatField(max_length=255, verbose_name='Longitude'),
        ),
    ]
