# Generated by Django 2.2.10 on 2020-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200604_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lat',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lng',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
    ]
