# Generated by Django 2.2.10 on 2020-06-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_profile_onesignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='onesignal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Onesignal'),
        ),
    ]
