# Generated by Django 2.2.10 on 2020-06-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200605_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('done', 'Realizado'), ('recused', 'Recusado'), ('approved', 'Aprovado'), ('requested', 'Aguardando aprovação')], default='requested', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceprofessional',
            name='status',
            field=models.CharField(choices=[('recused', 'Recusado'), ('approved', 'Aprovado'), ('requested', 'Aguardando aprovação')], default='requested', max_length=255, verbose_name='Status'),
        ),
    ]
