# Generated by Django 2.2.10 on 2020-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20200605_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('done', 'Realizado'), ('approved', 'Aprovado'), ('canceled', 'Cancelado'), ('requested', 'Aguardando aprovação')], default='requested', max_length=255, verbose_name='Status'),
        ),
    ]
